name: 'airelibre_analytics'
version: '1.0.0'

profile: 'airelibre_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"
  
vars:
  delta_dt_h: 1
  loc_asucentro:
    lat: -25.2968
    lon: -57.6350

models:
  airelibre_analytics:
    intermediate:
      +materialized: view
    marts:
      +materialized: table
