name: 'airelibre_analytics'
version: '1.0.0'

profile: 'airelibre_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"
  
vars:
  delta_dt_h: 1
  loc_asucentro:
    lat: -25.282108
    lon: -57.635053
  valid_params:
    min_readings: 24*60
    min_coverage_frac: 0.5
    excluded_location_ids:
      - c52b6116
      - a80d7ed9

models:
  airelibre_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: table # set to ephemeral later
    marts:
      +materialized: table
