paths:
  raw_dir: "data/raw"
  db_path: "data/airelibre_dw.duckdb"
  notebooks_dir: "notebooks"
  dbt_dir: "dbt"

ingestion:
  start_datetime: "2024-01-01T00:00:00Z"
  end_datetime: "2025-01-01T00:00:00Z" # (null for end_datetime=now())
  delta_hours: 1 # FIXED - DO NOT CHANGE (this is the standard)
  requests:
    api_url: "https://api.airelib.re/api/v1/aqi"
    max_retries: 3
    backoff_base_seconds: 2
    timeout_seconds: 5

staging:
  coord_decimal_precision: 4

core:
  coord_tolerance: 0.01 # ~1km of jitter is allowed in sensor location
