x-common-variables: &common-vars
  CONFIG_PATH: /app/config.yaml
  DUCKDB_PATH: /app/data/airelibre_dw.duckdb

services:
  dashboard:
    build:
      context: .
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    image: airelibre-analytics:latest
    command: >
      streamlit run src/dashboard/app.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      <<: *common-vars
      STREAMLIT_CONFIG_FILE: /app/.streamlit/config.toml
    restart: always

  pipeline:
    build:
      context: .
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    image: airelibre-analytics:latest
    command: bash run_pipeline.sh
    volumes:
      - .:/app
    environment:
      <<: *common-vars
      DBT_PROFILES_DIR: /app/dbt
      DBT_PROJECT_DIR: /app/dbt
